### ISSUE TITLE
Passing multiple tags in <cucumberRunner.excludeTags>

### ISSUE THREAD

**Issue by varaprasad-pakalapati** [eu-evops/cucumber-runner-maven-plugin#9]
Hi,

Can you let me know how to pass multiple tags in `<cucumberRunner.includeTags>` or `<cucumberRunner.excludeTags>` in POM properties.

I am able to pass in the plugin configuration using 
```
<excludeTags>
  <excludeTag>@manual<excludeTag>
  <excludeTag>@ios<excludeTag>
<excludeTags>
```

But I was unable to pass multiple tags from properties. 

I tried to use `'mvn cucumber-runner:run -Dcucumber.options="--tags ~@manual --tags ~@ios"'` from jenkins. It is completely ignoring the `-Dcucumber.options`.

Can you help me with this please?

Thanks
Vara

**Comment by sponte** [comment]
Hi @varaprasad-pakalapati, in order to exclude tags using command line parameters, you would specify:

```
mvn cucumber-runner:run -DcucumberRunner.excludeTags=@wip,@manual
```

The `cucumber.options` option is completely ignored as `cucumber-runner-maven-plugin` will overwrite most properties.

Hope this helps.

**Comment by varaprasad-pakalapati** [comment]
@sponte works like charm.

Thanks a lot

**Comment by sponte** [comment]
Cool :)
